export const JOIN_API_PATH = '/api/join';
export const LOGIN_API_PATH = '/api/login';
export const EMAIL_OVERLAP_CHECK_API_PATH = '/api/check-email';
export const NICKNAME_OVERLAP_CHECK_API_PATH = `/api/check-nickname`; //query: nickname
export const PHONE_AUTHENTICATION_API_PATH = '/api/certification';
export const PHONE_OVERLAP_CHECK_API_PATH = '/api/check-phone';
export const RESET_PASSWORD_API_PATH = '/api/resetpwd';
export const FIND_USER_API_PATH = '/api/check-user';
export const FIND_EMAIL_API_PATH = '/api/show-email';
export const REGENERATION_REFRESH_API_PATH = '/user/refresh';
export const LOGOUT_API_PATH = '/user/logout';
export const PHONE_AUTHENTICATION_ONLY_USER_API_PATH = '/api/certification-onlyuser';
export const SOCIAL_LOGIN_API_PATH = '/api/oauth2-request';
export const SOCIAL_ADDITIONAL_INFO_API_PATH = '/api/oauth2-join';
export const SOCIAL_SILENT_LOGIN_API_PATH = '/api/oauth2-access';
